create table
  public.ideas (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    description text not null,
    user_id uuid not null default auth.uid (),
    constraint ideas_pkey primary key (id)
  ) tablespace pg_default;

  create table
  public.profiles (
    id uuid not null,
    created_at timestamp with time zone null default now(),
    updated_at timestamp with time zone null,
    username text null,
    firstname text null,
    lastname text null,
    constraint profiles_pkey primary key (id),
    constraint profiles_username_key unique (username)
  ) tablespace pg_default;

  create table
  public.conversations (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    participants text[] not null,
    constraint conversations_pkey primary key (id)
  ) tablespace pg_default;

  create table
  public.messages (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    sender uuid not null,
    content text not null,
    conversation_id bigint not null,
    constraint messages_pkey primary key (id)
  ) tablespace pg_default;